package javaapplication1;

//import javaapplication1.Welcome;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

    /**
     *
     */
    public int i=0;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dblarrow = new javax.swing.JButton();
        CAbtn = new javax.swing.JButton();
        BPbtn = new javax.swing.JButton();
        PTbtn = new javax.swing.JButton();
        ABbtn = new javax.swing.JButton();
        OCbtn = new javax.swing.JButton();
        BIbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dblarrow.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\HMS ICON\\two arrow.png")); // NOI18N
        dblarrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dblarrowActionPerformed(evt);
            }
        });
        getContentPane().add(dblarrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, -1, -1));

        CAbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\HMS ICON\\add new patient.png")); // NOI18N
        CAbtn.setText("Create Account");
        CAbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        CAbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAbtnActionPerformed(evt);
            }
        });
        getContentPane().add(CAbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 89, -1, -1));

        BPbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-bill-50.png")); // NOI18N
        BPbtn.setText("Bill payment");
        BPbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        BPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPbtnActionPerformed(evt);
            }
        });
        getContentPane().add(BPbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 346, -1, -1));

        PTbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-advertisement-page-48.png")); // NOI18N
        PTbtn.setText("Payment Transfer");
        PTbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        PTbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTbtnActionPerformed(evt);
            }
        });
        getContentPane().add(PTbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        ABbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-coins-48.png")); // NOI18N
        ABbtn.setText("Account Balance");
        ABbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        ABbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ABbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 175, -1, -1));

        OCbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-bank-64.png")); // NOI18N
        OCbtn.setText("Order Checkbook");
        OCbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        OCbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCbtnActionPerformed(evt);
            }
        });
        getContentPane().add(OCbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 432, -1, 55));

        BIbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-bank-64 (1).png")); // NOI18N
        BIbtn.setText("Bank Information");
        BIbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        BIbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIbtnActionPerformed(evt);
            }
        });
        getContentPane().add(BIbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 58));

        logoutbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\HMS ICON\\exit.png")); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\worldbank2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPbtnActionPerformed
        // TODO add your handling code here:
         new Billpayment().setVisible(true);
    }//GEN-LAST:event_BPbtnActionPerformed

    private void BIbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIbtnActionPerformed
        // TODO add your handling code here:
        new Bank_Information().setVisible(true);
    }//GEN-LAST:event_BIbtnActionPerformed

    private void CAbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAbtnActionPerformed
        // TODO add your handling code here:
        new Create_Account().setVisible(true);
    }//GEN-LAST:event_CAbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            setVisible(false);
            new Welcome().setVisible(true);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void dblarrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dblarrowActionPerformed
        // TODO add your handling code here:
        if(i==0)
        {
            CAbtn.setLocation(90, 30);
            ABbtn.setLocation(333, 30);
            PTbtn.setLocation(576, 30);
            BPbtn.setLocation(819, 30);
            OCbtn.setLocation(1062, 30);
            BIbtn.setLocation(1305, 89);
            logoutbtn.setLocation(1305, 89);
            i=1;
            
        }
        else
        {
            CAbtn.setLocation(10, 107);
            ABbtn.setLocation(10, 184);
            PTbtn.setLocation(10, 261);
            BPbtn.setLocation(10, 338);
            OCbtn.setLocation(10, 415);
            BIbtn.setLocation(10, 567);
            logoutbtn.setLocation(10,644);
            i=0;
        }
    }//GEN-LAST:event_dblarrowActionPerformed

    private void OCbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCbtnActionPerformed
        // TODO add your handling code here:
         new OrderChequeBook().setVisible(true);
    }//GEN-LAST:event_OCbtnActionPerformed

    private void PTbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTbtnActionPerformed
        // TODO add your handling code here:
         new PaymentTransfer().setVisible(true);
    }//GEN-LAST:event_PTbtnActionPerformed

    private void ABbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABbtnActionPerformed
        // TODO add your handling code here:
        new Account_Balance().setVisible(true);
    }//GEN-LAST:event_ABbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABbtn;
    private javax.swing.JButton BIbtn;
    private javax.swing.JButton BPbtn;
    private javax.swing.JButton CAbtn;
    private javax.swing.JButton OCbtn;
    private javax.swing.JButton PTbtn;
    private javax.swing.JButton dblarrow;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutbtn;
    // End of variables declaration//GEN-END:variables
}
